imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: menu.yml }
    - { resource: ../../vendor/nitra/doctrine-behaviors/config/orm-services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'NitraTopsBundle:Form:fields.html.twig'
            - 'NitraUploadBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ AdmingeneratorGeneratorBundle , NitraUploadBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: 
            apply_to: ["\.css$", "\.less$"]
        lessphp: 
            apply_to: "\.less$"
        #cssmin: 
        #    apply_to: ["\.css$", "\.less$"]
        #jsmin: 
        #    apply_to: "\.js$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        filters:
            softdeleteable:
                class: Admingenerator\GeneratorBundle\Filter\SoftDeleteableFilter
                enabled: true

        hydrators:
              KeyPair: Admingenerator\GeneratorBundle\Hydrators\KeyPairHydrator      

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: MillwrightMenuBundle:Default:knp_menu.html.twig

    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default
    
admingenerator_generator:
    base_admin_template: ::base_admin.html.twig
    use_doctrine_orm: true
    stylesheets: []
#    templates_dirs: [ %kernel.root_dir%/../vendor/nitra/nitra-theme-bundle/Nitra/NitraThemeBundle/Resources/templates ]
    twig:
        use_localized_date: true
        use_form_resources: true
        date_format: 'd-M-Y'
        localized_date_format: 'medium'
        localized_datetime_format: 'medium'
        datetime_format: 'dd-MM-Y H:i'  
        number_format:
            decimal: 2
            decimal_point: ','
            thousand_separator: ' '
            
services:
    upload_handler:
        class:        Nitra\UploadBundle\UploadHandler
        arguments:    ["@doctrine.orm.entity_manager", "@router", "@kernel"]