millwright_menu:
    renderers:
        navigation: #menu type id
            renderer: null # custom renderer
            rendererOptions:
                template: AdmingeneratorGeneratorBundle::knp_menu.html.twig  
                ancestorClass: current active
                currentClass: current

    items: 
      finance:
        label: Финансы
      income:
        label: Поступление
        route: Nitra_TopsBundle_Income_list
      account:
        label: Счета
        route: Nitra_TopsBundle_Account_list
          
        
    
        
               
    tree: #menu containers
      main: #main container
        type: navigation # menu type id
        children:
          finance:
            children:
              income: ~
              account: ~
             

      