millwright_menu:
    renderers:
        navigation: #menu type id
            renderer: null # custom renderer
            rendererOptions:
                template: AdmingeneratorGeneratorBundle::knp_menu.html.twig  
                ancestorClass: current active
                currentClass: current

    items: 
      finance:
        label: Финансы
      income:
        label: Поступление
        route: Nitra_TopsBundle_Income_list
      account:
        label: Счета
        route: Nitra_TopsBundle_Account_list
      expense:
        label: Расходы
        route: Nitra_TopsBundle_Expense_list
      categoryExpense:
        label: Категории расход
        route: Nitra_TopsBundle_CategoryExpense_list
      catalog:
        label: Спарвочники
      buyer:
        route: Nitra_TopsBundle_Buyer_list
        label: Клиенты
      orders:
        route: Nitra_TopsBundle_Orders_list
        label: Заказы
      production:
        route: Nitra_TopsBundle_Production_list
        label: Продукция
      colors:
        route: Nitra_TopsBundle_Colors_list
        label: Цвета
      analytics_account:
        label: Активы по счетам
        route: nitra_tops_analitics_active_accountactive 
          
        
    
        
    tree: #menu containers
      main: #main container
        type: navigation # menu type id
        children:
          finance:
            children:
              income: ~
              expense: ~      
              analytics_account: ~
          catalog:
              children:
                account: ~
                categoryExpense: ~
                buyer: ~
                production: ~
                colors: ~
          orders:
                  
             

      