NitraTopsBundle_admin_nitra_tops_bundle_colors:
    resource: "@NitraTopsBundle/Controller/Colors/"
    type:     admingenerator
    prefix:   /admin/nitra_tops_bundle/colors

NitraTopsBundle_admin_nitra_tops_bundle_production:
    resource: "@NitraTopsBundle/Controller/Production/"
    type:     admingenerator
    prefix:   /production

NitraTopsBundle_admin_nitra_tops_bundle_orders:
    resource: "@NitraTopsBundle/Controller/Orders/"
    type:     admingenerator
    prefix:   /orders

NitraTopsBundle_admin_nitra_tops_bundle_buyer:
    resource: "@NitraTopsBundle/Controller/Buyer/"
    type:     admingenerator
    prefix:   /buyer

NitraTopsBundle_admin_nitra_tops_bundle_expense:
    resource: "@NitraTopsBundle/Controller/Expense/"
    type:     admingenerator
    prefix:   /expense

NitraTopsBundle_admin_nitra_tops_bundle_categoryExpense:
    resource: "@NitraTopsBundle/Controller/CategoryExpense/"
    type:     admingenerator
    prefix:   /category-expense

NitraTopsBundle_admin_nitra_tops_bundle_account:
    resource: "@NitraTopsBundle/Controller/Account/"
    type:     admingenerator
    prefix:   /account

NitraTopsBundle_admin_nitra_tops_bundle_income:
    resource: "@NitraTopsBundle/Controller/Income/"
    type:     admingenerator
    prefix:   /income
    
NitraTopsBundle_admin_nitra_tops_bundle_analitics:
    resource: "@NitraTopsBundle/Controller/Analitics/"
    type:     annotation
    prefix:   /analytics 
    
root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /orders
        permanent: true    
    