generator: admingenerator.generator.doctrine
params:
    model: Nitra\TopsBundle\Entity\Account
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: TopsBundle
    pk_requirement: ~
    fields: 
      name: {label: Название}
      requisites: {label: Реквизиты, addFormOptions: { required: false }}
      updatedAt: {label: Когда изменял}
      updatedBy: {label: Кто изменял}
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Список счетов
            display:  [name, requisites, updatedAt, updatedBy ]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: [name , requisites]
    new:
        params:
            title: Создание нового счета
            display: [name, requisites]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Редактирование счета \"%object%\"|{ %object%: Account.name }|"
            display: [name , requisites]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%:  Account.name  }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
