generator: admingenerator.generator.doctrine
params:
    model: Nitra\TopsBundle\Entity\CategoryExpanse
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: TopsBundle
    pk_requirement: ~
    fields: 
      name: {label: Название}
      updatedAt: {label: Когда изменял}
      updatedBy: {label: Кто изменял}
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Список категорий расходов
            display: [name,updatedAt, updatedBy ]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: [name]
    new:
        params:
            title: Создание новой категории расходов
            display: [name]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Редактирование категории расходов \"%object%\"|{ %object%: CategoryExpanse.name }|"
            display: [name]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: CategoryExpanse.name }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
