generator: admingenerator.generator.doctrine
params:
    model: Nitra\TopsBundle\Entity\Colors
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: TopsBundle
    pk_requirement: ~
    fields: 
        name: {label: Название}
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for TopsBundle
            display: ~
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: Добавление нового цвета
            display: [name]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Редактирование цвета \"%object%\"|{ %object%: Colors.name }|"
            display: [name]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Colors.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
