generator: admingenerator.generator.doctrine
params:
    model: Nitra\TopsBundle\Entity\Expanse
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: TopsBundle
    pk_requirement: ~
    fields: 
      id: { label: № }
      name: {label: Название}
      account: { label:Счет }
      categoryExpanse: {label: Категории расходов}
      comment: {label: Коментарий}
      amount: { label: Сумма }   
      date: { label: Дата }
      updatedAt: {label: Когда изменял}
      updatedBy: {label: Кто изменял}
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for TopsBundle
            display: [id, date, amount, account,categoryExpanse, comment, updatedAt, updatedBy]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: [date, account,categoryExpanse, comment]
    new:
        params:
            title: Создание нового расхода
            display:  [date, amount, account,categoryExpanse, comment]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Редактирование расходы \"%object%\"|{ %object%: Expanse.id }|"
            display:  [date, amount, account,categoryExpanse, comment]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Expanse.id }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
