generator: admingenerator.generator.doctrine
params:
    model: Nitra\TopsBundle\Entity\Income
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: TopsBundle
    pk_requirement: ~
    fields:
      id: { label: № }
      date: { label: Дата }
      amount: { label: Сумма }   
      account: { label: Счет }
      comment: { label: Коментарий}
      orders: { label: Заказ}
  
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Список поступлений 
            display: [id, date, amount, orders, account, comment]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display:  [id, date, amount,orders, account, comment]
    new:
        params:
            title: Создание поступления
            display: [date, amount,orders, account, comment]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: Income.id }|"
            display: [date, amount, account, comment]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Income.id }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
