generator: admingenerator.generator.doctrine
params:
    model: Nitra\TopsBundle\Entity\Production
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: TopsBundle
    pk_requirement: ~
    fields: 
        id: {label: Код}
        name: {label: Название}
        art: {label: Артикул}
        cost: {label: Цена}
        assemblyCost: {label: Цена сборки}
        file:  {label: Документы}
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Список продуктов
            display: [id, art, name, cost, assemblyCost, file]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: [art, name ]
    new:
        params:
            title: Добавление новго продукта
            display: [art, name, cost, assemblyCost, file ]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Редактирование продукта \"%object%\"|{ %object%: Production.name }|"
            display: [art, name, cost, assemblyCost, file ]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: production.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
